<?php

return [
    'name' => env('APP_NAME', 'gozviet'),
    'brand_mark' => env('APP_BRAND_MARK', ''),
    'brand_suffix' => env('APP_BRAND_SUFFIX', 'gozviet'),
    'contact_phone' => env('APP_CONTACT_PHONE', '0981952856'),
    'contact_email' => env('APP_CONTACT_EMAIL', 'goz86@gmail.com'),
    'geocode_verify_ssl' => (bool) env('GEOCODE_VERIFY_SSL', env('APP_ENV', 'production') !== 'local'),
    'platform_bank' => [
        'bank_name'    => env('PLATFORM_BANK_NAME', 'VietinBank'),
        'bank_bin'     => env('PLATFORM_BANK_BIN', '970415'),
        'account'      => env('PLATFORM_BANK_ACCOUNT', '108887132437'),
        'account_name' => env('PLATFORM_BANK_ACCOUNT_NAME', 'HỒ NGỌC THANH TÂM'),
    ],
    'env' => env('APP_ENV', 'production'),
    'debug' => (bool) env('APP_DEBUG', false),
    'url' => env('APP_URL', 'http://localhost:8000'),
    'asset_url' => env('ASSET_URL'),
    'timezone' => 'Asia/Ho_Chi_Minh',
    'locale' => 'vi',
    'fallback_locale' => 'en',
    'faker_locale' => 'vi_VN',
    'key' => env('APP_KEY'),
    'cipher' => 'AES-256-CBC',
    'providers' => [
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        Laravel\Sanctum\SanctumServiceProvider::class,
        App\Providers\AppServiceProvider::class,
    ],
    'aliases' => [
    ],
];
